language: scala
dist: xenial

jdk:
  - openjdk8
  - openjdk11

scala:
   - 2.12.9
   - 2.13.0

before_script:
  - sbt stage

script:
  - sbt scalafmtSbtCheck scalafmtCheckAll
  - sbt ++$TRAVIS_SCALA_VERSION test
  - ./build.sh

matrix:
  allow_failures:
    - jdk: openjdk8

cache:
  directories:
    - "$HOME/.cache/coursier/v1"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
